# Site title
title: "The Third Bit"
author: Greg Wilson
email: gvwilson@third-bit.com
permalink: /:year/:month/:day/:title.html
url: http://third-bit.com

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
repository: <USERNAME>/<PROJECT>

# Files and directories that are not to be copied.
exclude:
  - Makefile
