# Jekyll configuration

name: "Third Bit"
description: "Start now. Use what you have. Help those you can."
author: "Greg Wilson"

# URL is currently only used only for the RSS feed in feed.xml
url: "http://third-bit.com/feed.xml"

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
repository: <USERNAME>/<PROJECT>

# Set this to your UA-# value, or "" to disable the block completely
gaaccount: "UA-1301159-1"

# The 'comments' setting enables comments. You'll need to select either
# disqus or isso below to choose a comment system.
comments: true

# Set this to your public isso URL to enable comments via isso. Set to "" to disable isso.
isso: ""

# Set this to your disqus shortname to enable comments via disqus. Set to "" to disable disqus.
disqus: "thirdbit"

# URL for "How to Teach Programming" on Lulu.com
teaching_lulu_url: http://www.lulu.com/shop/greg-wilson/how-to-teach-programming-and-other-things/paperback/product-23439331.html

# Standard configuration variables.
permalink: /:year/:month/:day/:title.html
paginate: 10
highlighter: rouge
markdown: kramdown
plugins:
  - "jekyll-paginate"
  - "jekyll-redirect-from"
exclude: ["README.md", "LICENSE"]
